from typing import Any

import pandas as pd

from app.services.forecast_engine import run_forecast
from app.services.insight_engine import generate_insights
from app.services.llm import generate_text, llm_is_enabled
from app.services.profiler import profile_dataframe


async def generate_report(df: pd.DataFrame, filename: str) -> dict[str, Any]:
    profile = profile_dataframe(df)
    insights = generate_insights(df)
    forecast = None
    try:
        forecast = run_forecast(df, periods=3)
    except ValueError:
        pass

    structured = {
        "filename": filename,
        "profile": {
            "rows": profile["rows"],
            "columns": profile["columns"],
            "quality_score": profile["quality_score"],
            "completeness_pct": profile["completeness_pct"],
            "duplicate_rows": profile["duplicate_rows"],
        },
        "top_insights": insights[:8],
        "forecast": forecast,
    }

    llm_narrative = await _generate_narrative(structured)
    markdown = _build_markdown(structured, llm_narrative)

    return {
        "markdown": markdown,
        "structured": structured,
        "llm_enhanced": llm_narrative is not None,
    }


async def _generate_narrative(structured: dict[str, Any]) -> str | None:
    if not llm_is_enabled():
        return None
    insight_lines = "\n".join(
        f"- {i['title']}: {i['description']}" for i in structured["top_insights"][:5]
    )
    forecast_text = "No forecast available."
    if structured.get("forecast"):
        fc = structured["forecast"]
        forecast_text = (
            f"Model: {fc['model_used']}, target: {fc['target_column']}, "
            f"next value: {fc['forecast'][0]['value']}"
        )

    prompt = f"""You are a business analyst writing an executive report.
Dataset: {structured['filename']}
Rows: {structured['profile']['rows']}, Quality: {structured['profile']['quality_score']}/100
Key insights:
{insight_lines}
Forecast: {forecast_text}

Write markdown sections:
## Executive Summary
## Key Findings
## Risks and Opportunities
## Forecast Results
## Strategic Recommendations

Be concise, data-driven, and actionable. Do not invent numbers not provided."""

    return await generate_text(prompt)


def _build_markdown(structured: dict[str, Any], llm_narrative: str | None) -> str:
    if llm_narrative:
        header = f"# Executive Report: {structured['filename']}\n\n"
        footer = _template_footer(structured)
        return header + llm_narrative.strip() + "\n\n" + footer

    return _template_report(structured)


def _template_report(structured: dict[str, Any]) -> str:
    p = structured["profile"]
    lines = [
        f"# Executive Report: {structured['filename']}",
        "",
        "## Executive Summary",
        f"This dataset contains **{p['rows']}** records across **{p['columns']}** columns "
        f"with a data quality score of **{p['quality_score']}/100**.",
        "",
        "## Key Findings",
    ]
    for insight in structured["top_insights"][:5]:
        lines.append(f"- **{insight['title']}** — {insight['description']}")

    lines.extend(["", "## Risks and Opportunities"])
    if p["duplicate_rows"] > 0:
        lines.append(f"- Risk: {p['duplicate_rows']} duplicate rows may skew analysis.")
    if p["completeness_pct"] < 90:
        lines.append(f"- Risk: Data completeness is {p['completeness_pct']}%.")
    else:
        lines.append("- Opportunity: Strong data completeness supports reliable decisions.")

    lines.extend(["", "## Forecast Results"])
    fc = structured.get("forecast")
    if fc:
        for point in fc["forecast"]:
            lines.append(
                f"- {point['date']}: projected **{point['value']:,.2f}** "
                f"({fc['model_used']})"
            )
    else:
        lines.append("- Forecast unavailable — insufficient time-series data.")

    lines.extend(
        [
            "",
            "## Strategic Recommendations",
            "- Focus on top-performing categories identified in insights.",
            "- Address data quality issues before scaling analysis.",
            "- Monitor forecasted trends and adjust strategy quarterly.",
        ]
    )
    return "\n".join(lines)


def _template_footer(structured: dict[str, Any]) -> str:
    return (
        "---\n"
        f"*Report generated by Prisma AI. "
        f"Quality score: {structured['profile']['quality_score']}/100.*"
    )
